name: Build & test project
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.17-alpine3.15
    steps:
      - name: build
        run: go build -o bin/dungeon
